2996_reflection/reflection.md

Clarify that `template_arguments_of` is not only for specializations of class templates. Remove an extra comma.

Fix a few nitpicks.

---

2996_reflection/reflection.md

I'm not actually sure why `^Tag::type` works for EDG without a `typename`?

A few fixes to 'named_tuple'.

---

2996_reflection/reflection.md

Fix typo in example

---

2996_reflection/reflection.md

"Shall" in the library wording means that the behavior is undefined when such a requirement is not met by default.
Perhaps we just want ill-formedness, and "non-constant library call" ([[defns.nonconst.libcall]](https://eel.is/c++draft/defns.nonconst.libcall)) looks appropriate to me since these functions are all `consteval`.

Suggestion for removing UB in the library wording of P2996

---

2996_reflection/d2996r3.html
2996_reflection/reflection.md

Also:
- value_of -> extract
- reflect_value -> reflect
- new value_of, is_evaluation metafunctions
- tried to update all uses of "constant value" or "value" to "evaluation" (where appropriate)
- removed support for reflecting cast-expressions
- removed some details of historical discussion (e.g., alternative syntaxes) to avoid further bikeshedding
- editing pass over the entire paper (excluding library wording).

Lots of changes. Values and objects, not expressions, not "evaluations".

---

2996_reflection/d2996r3.html
2996_reflection/reflection.md

- Added section describing contexts in which splicers may not appear.
- Revised error-handling section to clarify position of the authors.
- Updated behavior of 'is_incomplete_type'.
- Updated ticker counter to work with updated 'is_incomplete_type' behavior.
- Added justification for restricting values to those of structural type.
- Comparing reflections of values uses 'template-argument-equivalent' notion.
- Added 'is_user_provided' metafunction.
- Clarified that 'parent_of' does return inline and anonymous namespaces.
- Note re: possible extensions to 'reflect_invoke'.
- Mandate that 'members_of'-queries require complete classes.
- Specify that 'members_of'-queries instantiate template specializations.

More updates.

---

2996_reflection/p2996r4.html
2996_reflection/reflection.md

Figured it was worth adding the example. Forgot this could happen too.

'^int & true' is also ambiguous.

---

2996_reflection/p2996r4.html
2996_reflection/reflection.md

- Updated revision log
- Broke `reflect_result` into {`reflect_value`, `reflect_object`, `reflect_function`}
- Updated Clang Godbolt links (TODO: check if any EDGs need updating)
- Clarified rules around comparing reflections of aliases, and linkage of templates specialized by them
- Revamped the member access APIs, as per discussions
- Added an `is_reflection` / `is_reflection_v` / `type_is_reflection` type-trait for the new primary type category occupied by `std::meta::info`.
- Renamed `test_type[s]` to `test_trait`
- Added `has_module_linkage` metafunction

Various updates (notably accessibility API).

---

2996_reflection/p2996r4.html
2996_reflection/reflection.md

- Typo fixes
- Remove `is_static` (we thought we did this yesterday)
- Split `name_of` into `name_of`/`u8name_of`.

Typo fixes and name_of changes.

---

2996_reflection/d2996r5.html
2996_reflection/reflection.md

One overload per function. Get rid of `access_pair`. Integrate some LEWG feedback.

One overload per accessibility function.

---

2996_reflection/d2996r5.html
2996_reflection/reflection.md

- Consistently use "represents" for reflections.
- Sub-bullets for 'plainly constant evaluated' exceptions.
- 'Denote' -> 'Designate' for splicing.
- 'respective' -> 'corresponding' in [basic.def.odr].
- Fix ADL wording.
- Reword 'basic.link' changes.
- consteval-only types: "ODR use" -> "immediate function context"
- Fix formatting typo in 'display_string_of' spec.
- 'names' -> 'designates' in [expr.ref] (also some typo fixes).
- Clean up 'basic.fundamental' as per Jens's feedback.
- Clean up 'dcl.init.general' per Jens's feedback.
- Clean up some enum-splicing wording.
- Re-word namespace splicing. Clean up nested-name-specifiers.
- Add `is_constructor_template` function.

Some 2024-06-27 and 2024-06-28 CWG updates.

---

2996_reflection/d2996r7.html
2996_reflection/reflection.md

Addressing the following CWG feedback:
- Add a note for why we're introducing "plainly constant evaluated"
- Add an example for "plainly constant evaluated"
- Rebase definition of "manifestly" onto "plainly"
- Disallow splices (and lambdas) from the controlling constant expression operand of `#if`
- Expand changes to `[expr.ref]` for splices (generally: "designates" instead of "is")
- Permit forming pointers-to-members through `&[:expr:]` syntax
- Rewrite `[expr.prim.splice]` to account for type and bit-field-ness of splice-expressions (and to be more clear)
- Don't unnecessarily preclude `extract` from producing a pointer-to-member-function.
cc @daveedvdv

Core wording changes and fixes

---

2996_reflection/p2996r8.html
2996_reflection/reflection.md

- s/unnamed name/unnamed
- Fix a silly mistake in the spec of the "Constant When" for `data_member_spec`
- Make sure reflections of typedefs are allowed for the data member type
- Fail constexpr if two data members will have the same name

Some final touch-ups on 'define_class' before LEWG presentation.

---

2996_reflection/p2996r8.html
2996_reflection/reflection.md

Also:
* don't fail constexpr if the function called multiple times on the same class, as long as it's called with equal values.
* all non-static data members are public.

Rename 'define_class' to 'define_aggregate'.

---

2996_reflection/p2996r8.html
2996_reflection/reflection.md

- Rewrite and unify the splicer grammars in one place. Overhaul template splicer grammar and handling.
- Rewrite grammar for _reflect-expression_ in terms of lookup (Daveed confirmed). Also fixes some minor wording bugs (e.g., a reflection of a non-type template parameter can yield an object in addition to a value).
- Get rid of `splice-namespace-qualifier`, `splice-template-argument` - it's just `splice-specifier`.
- Rewrite handling of CTAD, deduced placeholder types (i.e., `Concept auto var = value`).
- More careful attention to distinction between names and entities: Lift `*splice-specifier` out of `template-name` and `concept-name`, into `simple-template-id` and `type-constraint`.
- Apply changes discussed for _consteval-only types_ (i.e., immediate-escalation, consteval-erased …

Rewrite a lot of the core wording

---

2996_reflection/p2996r8.html
2996_reflection/reflection.md

Mainly two things.
1. I audited every use of _id-expression_ in the Standard, and found a bunch of places where we need to account for _splice-expressions_.
2. The "struct to struct of arrays" example is broken in the face of the new injected declaration rules (i.e., it injected a declaration from an instantiation into the global namespace) - this "fixes" the example against our latest understanding of those rules.

Audit id-expression. Fix "struct to struct of arrays" example.

---

2996_reflection/p2996r9.html
2996_reflection/reflection.md

Two minor nits.
1. Plainly constant-evaluated expressions are defined as non-dependent; saying so in [lex.phases] is redundant.
2. Adopt the phrasing for complete-class contexts that I used in [lex.phases] for _members-of-reachable_ (I like it better). Rename it _members-of-precedes_ since we use "precedes" instead of reachable now. Remove the note that follows, since it's now more obvious.

Minor updates.

---

2996_reflection/d2996r10.html
2996_reflection/reflection.md

Also remove a section no longer needed because variables are no longer plainly constant-evaluated.

Design changes section.

---

2996_reflection/d2996r11.html
2996_reflection/reflection.md

- Use `template for` in clang.
- Use `access_context` in clang and in paper.

[P2996] Update examples in the paper

---

2996_reflection/d2996r12.html
2996_reflection/reflection.md

Further edits to `access_context::current()` and `is_accessible`.
Other minor edits:
- Move `type_of` and friends earlier in `[meta.reflection]` such that the definition of _has-type_ precedes its usage in e.g., `is_const`.
- "same as that of _S_" instead of "same as _S_" (which makes it sound like _S_ is a type).
- Remove some more `{.sref}`s.

Post-CWG updates for 2025-04-25.

---

2996_reflection/d2996r12.html
2996_reflection/reflection.md

- Rename "naming class" to "designating class"; handle for _splice-expressions_
- `can_substitute` is false when the substitution forms a function whose type contains an undeduced placeholder type
- Add an example to `substitute` of when the definition gets instantiated
- Use `data_member_options` explicitly instead of leaning on `data_member_spec` in the example for `data_member_options::name_type`.

Updates before 2025-05-09 telecon.
