- md/deducing-this.md
> Added Ben and Me to authors.

- md/deducing-this.md
Added acknowledgements.
No diff in html because those changes are pending the barry_md.py merge.
> Added initial Acknowledgements.

- 1240_scalable_reflection/scalable-reflection.md
Add facilities to "invoke" TMP.
> Bridging computational and syntactic domains

- 2996_reflection/reflection.md
Dan Katz notes that he used those queries for his work mentioned in P3010.
> Add is_constructor, is_destructor, is_special_member

- 2996_reflection/reflection.md
Also includes a few wording tweaks
> Remove proposal of invalid reflections

- 2996_reflection/p2996r2.html
- 2996_reflection/reflection.md
Refine parsing rules for reflection operator a little.
Add constant-evaluation tweaking to deal with side effects.
> Updates to P2996 wording

- 2996_reflection/p2996r2.html
- 2996_reflection/reflection.md
> Add 'is_concept' metafunction.

- 2996_reflection/reflection.md
Hey, I am exictedly following your work on revision 2 of P2996. I hope you don't mind me providing this minor PR :)
> Fix three minor typos

- 2996_reflection/p2996r2.html
- 2996_reflection/reflection.md
I've discussed this one for a while with @daveedvdv , and we've both had success implementing it. He had no objections, suggested that I write up a motivating example, and propose the wording - so this is that :)
SG7 expressed interest in typeful reflection in Kona, so it's possible the example could help win some new fans to Team 2996.
> Add 'reflect_invoke' metafunction and motivating example.

- 2996_reflection/p2996r2.html
- 2996_reflection/reflection.md
Try to specify behavior of splices in the contexts of nested-name-specifiers, qualified-ids, and template-arguments.
> Nested-name-specifiers, terminology, template arguments.

- 2996_reflection/reflection.md
> Fix example

- 2996_reflection/d2996r4.html
- 2996_reflection/reflection.md
Data layout reflection, extract, reflect_invoke.
> Much of the remaining library wording.

- 2996_reflection/d2996r4.html
- 2996_reflection/reflection.md
* Update linkage model
* Update variant example
* ODR rules
* Splicing non-static data members in member access expressions
* Type splicing
* Template splicing
* Disallow concept splicing in the context of type parameter declarations
* Concept splicing
> Language wording updates.

- 2996_reflection/d2996r5.html
- 2996_reflection/reflection.md
The biggest change is the replacement of `name_of` and `qualified_name_of` with `identifier_of`, and the addition of certain functions to support that (`operator_of`, `define_static_string`). Also making a few other fixes and extensions that have been discussed. One or two small language fixes, too.
Updated all clang godbolts.
> Bunch of updates, mostly on the library side.

- 2996_reflection/d2996r5.html
- 2996_reflection/reflection.md
> Some post-LEWG updates

- 2996_reflection/Makefile
- 2996_reflection/d2996r6.html
- 2996_reflection/reflection.md
Staring an R6 with some more updates. Finally passed 100pgs, it's about time.
> More updates

- 2996_reflection/d2996r7.html
- 2996_reflection/reflection.md
Also try to put the other wording around the data_member_spec name on more solid footing.
> Wording for 'name_type' constructor.

- 2996_reflection/d2996r7.html
- 2996_reflection/reflection.md
> Wording fixes for identifier functions.

- 2996_reflection/Makefile
- 2996_reflection/p2996r8.html
- 2996_reflection/reflection.md
> LEWG operator feedback and fixes.

- 2996_reflection/p2996r8.html
- 2996_reflection/reflection.md
This change improves the quality of the P2996 proposal by a factor of exactly two.
> Two carets!!!!

- 2996_reflection/p2996r8.html
- 2996_reflection/reflection.md
- Also IFNDR for "indeterminately sequenced" evaluations
- Polish examples of rules for injected declarations given in [expr.const]
- Informal section discussing restrictions on injected declarations
> Always be updating

- 2996_reflection/d2996r9.html
- 2996_reflection/reflection.md
Also flesh out the revision history from R8, which CWG noted was incomplete and lacking.
> Last updates for January mailing.

- 2996_reflection/d2996r10.html
- 2996_reflection/reflection.md
- 3289_consteval_blocks/consteval-blocks.md
- 3289_consteval_blocks/d3289r2.html
- 3394_annotations/Makefile
- 3394_annotations/annotations.md
- 3394_annotations/d3394r2.html
Also a few other fixes we've discussed.
> Post-CWG updates.

- 2996_reflection/p2996r11.html
- 2996_reflection/reflection.md
> [P2996] Hubert-approved lambda rules.

- 2996_reflection/p2996r11.html
- 2996_reflection/reflection.md
Also fix a bunch of typos, removed overzealous `{sref}`s, obsolete wording, etc.
> Rebase on the working draft.
